# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/store/order
Content-Type: application/json

{
  "token": "372072042",
  "order": {
    "id": 0,
    "petId": 0,
    "quantity": 0,
    "shipDate": "2020-02-20T10:13:50.094Z",
    "status": "placed",
    "complete": true
  }
}

###

GET http://localhost:8080/store/order/0
Content-Type: application/json

{
  "token": "372072042"
}

###

DELETE http://localhost:8080/store/order/0
Content-Type: application/json

{
  "token": "372072042"
}

###